[tool.poetry]
name = "optimizer-worker"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
celery = "^5.4.0"
redis = "^5.0.7"
requests = "^2.32.3"
ortools = "^9.10.4067"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
